import type { Metadata } from "next";
import "./globals.css";
import { UsuarioProvider } from "./contexts/Provider/UsuarioProvider";
import { SalaProvider } from "./contexts/Provider/SalaProvider";
import { EquipeProvider } from "./contexts/Provider/EquipeProvider";
import { JogoProvider } from "./contexts/Provider/JogoProvider";
import { ParticipanteProvider } from "./contexts/Provider/ParticipanteProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <UsuarioProvider>
          <SalaProvider>
            <EquipeProvider>
              <ParticipanteProvider>
                <JogoProvider>{children}</JogoProvider>
              </ParticipanteProvider>
            </EquipeProvider>
          </SalaProvider>
        </UsuarioProvider>
      </body>
    </html>
  );
}
